INSERT INTO towns(town,region) VALUES ('Ang Mo Kio','North East');
INSERT INTO towns(town,region) VALUES ('Bedok','East');
INSERT INTO towns(town,region) VALUES ('Bishan','Central');
INSERT INTO towns(town,region) VALUES ('Boon Lay','West');
INSERT INTO towns(town,region) VALUES ('Bukit Batok','West');
INSERT INTO towns(town,region) VALUES ('Bukit Merah','Central');
INSERT INTO towns(town,region) VALUES ('Bukit Panjang','West');
INSERT INTO towns(town,region) VALUES ('Bukit Timah','Central');
INSERT INTO towns(town,region) VALUES ('Central Water Catchment','North');
INSERT INTO towns(town,region) VALUES ('Changi','East');
INSERT INTO towns(town,region) VALUES ('Changi Bay','East');
INSERT INTO towns(town,region) VALUES ('Choa Chu Kang','West');
INSERT INTO towns(town,region) VALUES ('Clementi','West');
INSERT INTO towns(town,region) VALUES ('Downtown Core','Central');
INSERT INTO towns(town,region) VALUES ('Geylang','Central');
INSERT INTO towns(town,region) VALUES ('Hougang','North East');
INSERT INTO towns(town,region) VALUES ('Jurong East','West');
INSERT INTO towns(town,region) VALUES ('Jurong West','West');
INSERT INTO towns(town,region) VALUES ('Kallang','Central');
INSERT INTO towns(town,region) VALUES ('Lim Chu Kang','North');
INSERT INTO towns(town,region) VALUES ('Mandai','North');
INSERT INTO towns(town,region) VALUES ('Marina East','Central');
INSERT INTO towns(town,region) VALUES ('Marina South','Central');
INSERT INTO towns(town,region) VALUES ('Marine Parade','Central');
INSERT INTO towns(town,region) VALUES ('Museum','Central');
INSERT INTO towns(town,region) VALUES ('Newton','Central');
INSERT INTO towns(town,region) VALUES ('North-Eastern Islands','North East');
INSERT INTO towns(town,region) VALUES ('Novena','Central');
INSERT INTO towns(town,region) VALUES ('Orchard','Central');
INSERT INTO towns(town,region) VALUES ('Outram','Central');
INSERT INTO towns(town,region) VALUES ('Pasir Ris','East');
INSERT INTO towns(town,region) VALUES ('Paya Lebar','East');
INSERT INTO towns(town,region) VALUES ('Pioneer','West');
INSERT INTO towns(town,region) VALUES ('Punggol','North East');
INSERT INTO towns(town,region) VALUES ('Queenstown','Central');
INSERT INTO towns(town,region) VALUES ('River Valley','Central');
INSERT INTO towns(town,region) VALUES ('Rochor','Central');
INSERT INTO towns(town,region) VALUES ('Seletar','North East');
INSERT INTO towns(town,region) VALUES ('Sembawang','North');
INSERT INTO towns(town,region) VALUES ('Sengkang','North East');
INSERT INTO towns(town,region) VALUES ('Serangoon','North East');
INSERT INTO towns(town,region) VALUES ('Simpang','North');
INSERT INTO towns(town,region) VALUES ('Singapore River','Central');
INSERT INTO towns(town,region) VALUES ('Southern Islands','Central');
INSERT INTO towns(town,region) VALUES ('Straits View','Central');
INSERT INTO towns(town,region) VALUES ('Sungei Kadut','North');
INSERT INTO towns(town,region) VALUES ('Tampines','East');
INSERT INTO towns(town,region) VALUES ('Tanglin','Central');
INSERT INTO towns(town,region) VALUES ('Tengah','West');
INSERT INTO towns(town,region) VALUES ('Toa Payoh','Central');
INSERT INTO towns(town,region) VALUES ('Tuas','West');
INSERT INTO towns(town,region) VALUES ('Western Islands','West');
INSERT INTO towns(town,region) VALUES ('Western Water Catchment','West');
INSERT INTO towns(town,region) VALUES ('Woodlands','North');
INSERT INTO towns(town,region) VALUES ('Yishun','North');
